prj_KohinorWeb/Controllers/AboutUsController.cs
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using prj_KohinorWeb.Models;
using System.Diagnostics;

namespace prj_KohinorWeb.Controllers
{
    public class AboutUsController : Controller
    {
        private readonly ILogger<AboutUsController> _logger;

        public AboutUsController(ILogger<AboutUsController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

    }
}

prj_KohinorWeb/Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using prj_KohinorWeb.Models;
using prj_KohinorWeb.Services;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Threading.Tasks;

namespace prj_KohinorWeb.Controllers
{
    public class ContactController : Controller
    {
        private readonly ILogger<ContactController> _logger;
        private readonly HttpClient _httpClient;
        private readonly EmailService _emailService;
        private readonly string _password = "ATATT3xFfGF0k9EZznDfnoKVVhwQ3FszS7J2Kp12iAshyvXg3LgnnC8aeSwgHcA-maS41lIboJY5ErWdQ2KLx0zJOAzQXoOjANSZYzRvvaioAbnEWy1vapq9XDJwdOE6_cLyxyRIm7dMF-ZGKagqom1dCfULxsU3lo3SYfkKRG41frxj6VWa_EQ=CD792A20"; // Replace with your actual API token
        private readonly string _username = "kevin.diaz@kohinorec.com";
      

        public ContactController(ILogger<ContactController> logger, HttpClient httpClient, EmailService emailService)
        {
            _logger = logger;
            _httpClient = httpClient;
            _emailService = emailService;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Support()
        {
            return View();
        }
        public IActionResult OrderSent()
        {
            return View();
        }
        [HttpPost]
        public async Task<JsonResult> SubmitContactForm([FromBody] ContactFormModel model)
        {
            if (!ModelState.IsValid)
            {
                return Json(new { success = false, message = "Por favor, completa todos los campos correctamente." });
            }
            try
            {

                var (isSuccess, message) = await _emailService.SendContactEmail(model);

                return Json(new { success = isSuccess, message });
            }
            catch (Exception ex)
            {

                return Json(new { success = false, message = "Ocurrió un error al enviar el formulario. Inténtalo de nuevo más tarde." });
            }
        }
        [HttpPost]
        public async Task<IActionResult> SubmitForm(WorkOrderViewModel formData)
        {
            // Construct the description parameter
            var description = new StringBuilder();
            description.AppendLine($"Nombre: {formData.Name}");
            description.AppendLine($"Email: {formData.Email}");
            description.AppendLine($"Telefono: {formData.PhoneNumber}");
            description.AppendLine($"Requerimiento: {formData.Subject}");
            description.AppendLine($"Empresa: {formData.Company}");
            description.AppendLine($"Instrucciones: {formData.Description}");

            // Create the payload
            var issuePayload = new IssuePayload
            {
                fields = new Fields
                {
                    project = new Project { key = "KDBSWEB" },
                    summary = formData.Subject,
                    description = description.ToString(),
                    issuetype = new IssueType { name = "Task" }
                }
            };

            // Convert the form data to JSON
            var jsonData = JsonConvert.SerializeObject(issuePayload);
            var content = new StringContent(jsonData, Encoding.UTF8, "application/json");

            // Encode the username and password for Basic Authentication
            var credentials = Convert.ToBase64String(Encoding.ASCII.GetBytes($"{_username}:{_password}"));
            _httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Basic", credentials);

            // Send the POST request to the API
            var response = await _httpClient.PostAsync("https://kohinor-team.atlassian.net/rest/api/2/issue", content);

            if (response.IsSuccessStatusCode)
            {
                // Set success message and return the view with the message
                ViewData["Message"] = "Your message has been sent successfully!";
            }
            else
            {
                // Set error message and return the view with the message
                ViewData["Message"] = "An error occurred while sending your message. Please try again.";
            }

            // Return the same view with the message
            return View("OrderSent"); // Make sure the view name matches your actual view name
        }
    }
}

prj_KohinorWeb/Views/Shared/_ContactForm.cshtml
@{
    ViewData["Title"] = "Contact Form Section";
}
<div class="contact-area ptb-100">
    <div class="container">
        <div class="section-title">
            <span>@language.Getkey("ContactSupport_Index_Span_Order")</span>
            <h2>@language.Getkey("ContactSupport_Index_h_Order_Title")</h2>
        </div>

        <form id="contactForm">
            <div class="row">
                <div class="col-lg-6 col-md-12">
                    <div class="form-group">
                        <label>@language.Getkey("ContactSupport_Index_form_label_YourName")</label>
                        <input type="text" name="name" id="fullName" class="form-control" placeholder="@language.Getkey("ContactSupport_Index_form_ph_YourName")" required data-error="@language.Getkey("ContactSupport_Index_form_error_YourName")">
                        <div class="help-block with-errors"></div>
                    </div>
                </div>
                <div class="col-lg-6 col-md-12">
                    <div class="form-group">
                        <label>@language.Getkey("ContactSupport_Index_form_label_Email")</label>
                        <input type="email" name="email" id="email" class="form-control" placeholder="@language.Getkey("ContactSupport_Index_form_ph_label_Email")" required data-error="@language.Getkey("ContactSupport_Index_form_error_label_Email")">
                        <div class="help-block with-errors"></div>
                    </div>
                </div>
                <div class="col-lg-6 col-md-12">
                    <div class="form-group">
                        <label>@language.Getkey("ContactSupport_Index_form_label_Phone")</label>
                        <input type="text" name="phone" id="phone" placeholder="@language.Getkey("ContactSupport_Index_form_ph_Phone")" required data-error="@language.Getkey("ContactSupport_Index_form_error_Phone")" class="form-control">
                        <div class="help-block with-errors"></div>
                    </div>
                </div>
                <div class="col-lg-6 col-md-12">
                    <div class="form-group">
                        <label>@language.Getkey("ContactSupport_Index_form_label_Subject")</label>
                        <input type="text" name="subject" id="subject" placeholder="@language.Getkey("ContactSupport_Index_form_ph_Subject")" class="form-control" required data-error="@language.Getkey("ContactSupport_Index_form_error_Subject")">
                        <div class="help-block with-errors"></div>
                    </div>
                </div>
                <div class="col-lg-12 col-md-12">
                    <div class="form-group">
                        <label>@language.Getkey("ContactSupport_Index_form_label_Company")</label>
                        <input type="text" name="company" id="company" placeholder="@language.Getkey("ContactSupport_Index_form_ph_Company")" class="form-control" required data-error="@language.Getkey("ContactSupport_Index_form_error_Company")">
                        <div class="help-block with-errors"></div>
                    </div>
                </div>
                <div class="col-lg-12 col-md-12">
                    <div class="form-group">
                        <label>@language.Getkey("ContactSupport_Index_form_label_YourMessage")</label>
                        <textarea name="description" class="form-control" id="description" placeholder="@language.Getkey("ContactSupport_Index_form_ph_YourMessage")" cols="30" rows="6" required data-error="@language.Getkey("ContactSupport_Index_form_error_YourMessage")"></textarea>
                        <div class="help-block with-errors"></div>
                    </div>
                </div>
                <div class="col-lg-12 col-md-12 mb-3">
                    <div id="form-message"></div>
                </div>
                <div class="col-lg-12 col-md-12">
                    <div class="send-btn">
                        <button type="submit" class="default-btn">@language.Getkey("ContactSupport_Index_form_button_SubmitNow")</button>
                    </div>
                    <div id="msgSubmit" class="h3 text-center hidden"></div>
                    <div class="clearfix"></div>
                </div>
            </div>
        </form>
    </div>
</div>
@section scripts{
    <style>

        .alert {
            margin-top: 15px;
            padding: 10px;
            border-radius: 5px;
        }

        .alert-success {
            background-color: #d4edda;
            color: #155724;
            border: 1px solid #c3e6cb;
        }

        .alert-danger {
            background-color: #f8d7da;
            color: #721c24;
            border: 1px solid #f5c6cb;
        }

        .d-none {
            display: none;
        }

    </style>
}

prj_KohinorWeb/Views/Shared/_ContactInformation.cshtml
@{
    ViewData["Title"] = "Contact Information Section";
}

<div class="contact-information-area pt-100 pb-75">
    <div class="container">
        <div class="section-title">
            <span>@language.Getkey("ContactUs_Index_Span_ContactInfo")</span>
            <h2>@language.Getkey("ContactUs_Index_Span_ContactInfo_Title")</h2>
        </div>

        <div class="row justify-content-center">
            <div class="col-lg-3 col-md-6">
                <div class="contact-information-card overview-area">
                    <div class="icon">
                        <i class="ri-map-pin-line"></i>
                    </div>
                    <h3>@language.Getkey("Home_Footer_Span_Location"):</h3>
                    <p>@language.Getkey("Principal_Location")</p>
                </div>
            </div>

            <div class="col-lg-3 col-md-6">
                <div class="contact-information-card overview-area">
                    <div class="icon">
                        <i class="ri-mail-line"></i>
                    </div>
                    <h3>@language.Getkey("Home_Footer_Span_Email"):</h3>
                    <p><a href="mailto:@language.Getkey("Principal_Email")">@language.Getkey("Principal_Email")</a> <br> <a href="mailto:@language.Getkey("Secondary_Email")">@language.Getkey("Secondary_Email")</a></p>
                </div>
            </div>

            <div class="col-lg-3 col-md-6">
                <div class="contact-information-card overview-area">
                    <div class="icon">
                        <i class="ri-phone-line"></i>
                    </div>
                    <h3>@language.Getkey("Home_Footer_Span_Phone"):</h3>
                    <p><a href="tel:@language.Getkey("Principal_Tel")">@language.Getkey("Principal_Tel")</a> <br> <a href="tel:@language.Getkey("Secondary_Tel")">@language.Getkey("Secondary_Tel")</a></p>
                </div>
            </div>

            <div class="col-lg-3 col-md-6">
                <div class="contact-information-card overview-area">
                    <div class="icon">
                        <i class="ri-printer-line"></i>
                    </div>
                    <h3>@language.Getkey("Home_Footer_Span_Support"):</h3>
                    <p><a href="tel:@language.Getkey("Secondary_Tel_1")">@language.Getkey("Secondary_Tel_1")</a> <br> <a href="tel:121298765436709">+1-212-9876543670</a></p>
                </div>
            </div>
        </div>
    </div>
</div>

prj_KohinorWeb/Views/Shared/_Footer.cshtml
@{
    ViewData["Title"] = "Footer";
}

<div class="container">
    <div class="row justify-content-center">
        <div class="col-lg-3 col-md-6">
            <div class="single-footer-widget" data-aos="fade-up" data-aos-delay="50" data-aos-duration="500" data-aos-once="true">
                <div class="widget-logo">
                    <img src="~/Kohinor/images/logos/Kohinor.png" class="black-logo" alt="image" style="width:175px"/>
                    <img src="~/Kohinor/images/logos/Kohinor-Dark.png" class="white-logo" alt="image" style="width:175px"/>
                </div>
                <p>@language.Getkey("Home_Footer_p_GetUpdates")</p>

                <form class="newsletter-form" data-bs-toggle="validator">
                    <input type="email" class="input-newsletter" placeholder="@language.Getkey("Home_Footer_Placeholder_Email")" name="EMAIL" required autocomplete="off">

                    <button type="submit" class="default-btn">@language.Getkey("Home_Footer_Button_Subscribe")</button>
                    <div id="validator-newsletter" class="form-result"></div>
                </form>

                <ul class="widget-social">
                    <li>
                        <a href="https://www.facebook.com/EnvyTheme" target="_blank">
                            <i class="ri-facebook-fill"></i>
                        </a>
                    </li>
                    <li>
                        <a href="https://twitter.com/?lang=en" target="_blank">
                            <i class="ri-twitter-fill"></i>
                        </a>
                    </li>
                    <li>
                        <a href="https://www.instagram.com/" target="_blank">
                            <i class="ri-instagram-line"></i>
                        </a>
                    </li>
                    <li>
                        <a href="https://www.linkedin.com/signup" target="_blank">
                            <i class="ri-linkedin-line"></i>
                        </a>
                    </li>
                </ul>
            </div>
        </div>

        <div class="col-lg-3 col-md-6">
            <div class="single-footer-widget ps-5" data-aos="fade-up" data-aos-delay="60" data-aos-duration="600" data-aos-once="true">
                <h3>@language.Getkey("Home_Footer_h_CompanyTeam")</h3>

                <ul class="quick-links">
                    @*<li><a asp-area="" asp-controller="AboutUs" asp-action="Index">@language.Getkey("Home_Footer_Anchor_CompanyTeam")</a></li>*@
                    @*<li><a asp-area="" asp-controller="Home" asp-action="Index">@language.Getkey("Home_Footer_Anchor_NewsAndBlog")</a></li>*@
                    <li><a asp-area="" asp-controller="AboutUs" asp-action="Index">@language.Getkey("Home_Footer_Anchor_AboutUs")</a></li>
                    @*<li><a asp-area="" asp-controller="Home" asp-action="Index">@language.Getkey("Home_Footer_Anchor_Clients")</a></li>*@
                    @*<li><a asp-area="" asp-controller="Contact" asp-action="Support">@language.Getkey("Home_Footer_Anchor_Support")</a></li>*@
                    <li><a asp-area="" asp-controller="Contact" asp-action="Index">@language.Getkey("Home_Footer_Anchor_ContactUs")</a></li>
                </ul>
            </div>
        </div>

        <div class="col-lg-3 col-md-6">
            <div class="single-footer-widget ps-5" data-aos="fade-up" data-aos-delay="70" data-aos-duration="700" data-aos-once="true">
                <h3>Resources</h3>

                <ul class="quick-links">
                    @*<li><a asp-area="" asp-controller="Home" asp-action="Index">@language.Getkey("Home_Footer_Anchor_Security")</a></li>*@
                    @*<li><a asp-area="" asp-controller="Home" asp-action="Index">@language.Getkey("Home_Footer_Anchor_FAQ")</a></li>*@
                    <li><a asp-area="" asp-controller="Home" asp-action="Privacy">@language.Getkey("Home_Footer_Anchor_PrivacyPolicy")</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Terms">@language.Getkey("Home_Footer_Anchor_Terms")</a></li>
                    
                </ul>
            </div>
        </div>

        <div class="col-lg-3 col-md-6">
            <div class="single-footer-widget" data-aos="fade-up" data-aos-delay="80" data-aos-duration="800" data-aos-once="true">
                <h3>Contact Info</h3>

                <ul class="info-links">
                    <li><span>@language.Getkey("Home_Footer_Span_Location"):</span> @language.Getkey("Principal_Location")</li>
                    <li><span>@language.Getkey("Home_Footer_Span_Email"):</span> <a href="mailto:@language.Getkey("Principal_Email")">@language.Getkey("Principal_Email")</a></li>
                    <li><span>@language.Getkey("Home_Footer_Span_Phone"):</span> <a href="tel:@language.Getkey("Principal_Tel")">@language.Getkey("Principal_Tel")</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>

<div class="copyright-area">
    <div class="container">
        <div class="copyright-area-content">
            <p>
                @language.Getkey("Principal_Copyright")
                <a href="#" target="_blank">
                    @language.Getkey("Principal_Company")
                </a>
            </p>
        </div>
    </div>
</div>

prj_KohinorWeb/Views/Shared/_News.cshtml
@{
    ViewData["Title"] = "News Section";
}

<div class="getting-started-area pt-100 pb-75">
    <div class="container">
        <div class="section-title">
            <span>@language.Getkey("Home_Index_Span_News")</span>
            <h2>@language.Getkey("Home_Index_h_News_Title")</h2>
        </div>

        <div class="row justify-content-center">
            <div class="col-lg-3 col-sm-6">
                <div class="single-getting-started-card" data-aos="fade-up" data-aos-delay="50" data-aos-duration="500" data-aos-once="true">
                    <div class="getting-image">
                        <img src="~/Snuff/assets/images/getting-started/getting-1.png" alt="image">
                    </div>
                    <h3>@language.Getkey("Home_Index_h_News_Card_1")</h3>
                    <p>@language.Getkey("Home_Index_p_News_Card_1")</p>
                </div>
            </div>

            <div class="col-lg-3 col-sm-6">
                <div class="single-getting-started-card" data-aos="fade-up" data-aos-delay="60" data-aos-duration="600" data-aos-once="true">
                    <div class="getting-image">
                        <img src="~/Snuff/assets/images/explore/explore-6.png" alt="image">
                    </div>
                    <h3>@language.Getkey("Home_Index_h_News_Card_2")</h3>
                    <p>@language.Getkey("Home_Index_p_News_Card_2")</p>
                </div>
            </div>

            <div class="col-lg-3 col-sm-6">
                <div class="single-getting-started-card" data-aos="fade-up" data-aos-delay="70" data-aos-duration="700" data-aos-once="true">
                    <div class="getting-image">
                        <img src="~/Snuff/assets/images/main-banner/line-graph.png" alt="image">
                    </div>
                    <h3>@language.Getkey("Home_Index_h_News_Card_3")</h3>
                    <p>@language.Getkey("Home_Index_p_News_Card_3")</p>
                </div>
            </div>

            <div class="col-lg-3 col-sm-6">
                <div class="single-getting-started-card" data-aos="fade-up" data-aos-delay="80" data-aos-duration="800" data-aos-once="true">
                    <div class="getting-image">
                        <img src="~/Snuff/assets/images/benefits/benefits-5.png" alt="image">
                    </div>
                    <h3>@language.Getkey("Home_Index_h_News_Card_4")</h3>
                    <p>@language.Getkey("Home_Index_p_News_Card_4")</p>
                </div>
            </div>
        </div>
    </div>
</div>

prj_KohinorWeb/Views/Shared/_OurPlansLITE.cshtml
@{
    ViewData["Title"] = "Our Plans Section";
}

<div class="global-transfers-area pt-100 pb-75">
    <div class="container">
        <div class="section-title">
            <span>@language.Getkey("Pricing_Index_Span_OurPricingPlans")</span>
            <h2>@language.Getkey("Pricing_Index_h_OurPricingPlans_Desc")</h2>
        </div>

        <div class="row justify-content-center">
            <div class="col-lg-3 col-md-6">
                <div class="single-pricing-table" data-aos="fade-up" data-aos-delay="50" data-aos-duration="500" data-aos-once="true">
                    <div class="pricing-header">
                        <h3>@language.Getkey("Pricing_Index_h_Standard")</h3>
                    </div>
                    <div class="price">$20 <span>@language.Getkey("Pricing_Index_span_PerMonthly")</span></div>
                    <div class="pricing-btn">
                        <a asp-area="" asp-controller="Contact" asp-action="Index" class="default-btn">@language.Getkey("Pricing_Index_a_ChooseThisPlan")</a>
                    </div>
                    <ul class="features-list">
                        <li><i class="ri-check-line"></i> Free Mobile & Online App</li>
                        <li><i class="ri-check-line"></i> Online System</li>
                        <li><i class="ri-check-line"></i> Data full Access</li>
                        <li><i class="ri-check-line"></i> 1 Business Mastercard</li>
                        <li><i class="ri-check-line"></i> International Payment</li>
                        <li><i class="ri-check-line"></i> Support Unlimited</li>
                    </ul>
                </div>
            </div>

            <div class="col-lg-3 col-md-6">
                <div class="single-pricing-table" data-aos="fade-up" data-aos-delay="60" data-aos-duration="600" data-aos-once="true">
                    <div class="pricing-header">
                        <h3>@language.Getkey("Pricing_Index_h_Business")</h3>
                    </div>
                    <div class="price">$25 <span>@language.Getkey("Pricing_Index_span_PerMonthly")</span></div>
                    <div class="pricing-btn">
                        <a asp-area="" asp-controller="Contact" asp-action="Index" class="default-btn">@language.Getkey("Pricing_Index_a_ChooseThisPlan")</a>
                    </div>
                    <ul class="features-list">
                        <li><i class="ri-check-line"></i> Free Mobile & Online App</li>
                        <li><i class="ri-check-line"></i> Online System</li>
                        <li><i class="ri-check-line"></i> Data full Access</li>
                        <li><i class="ri-check-line"></i> 1 Business Mastercard</li>
                        <li><i class="ri-check-line"></i> International Payment</li>
                        <li><i class="ri-check-line"></i> Support Unlimited</li>
                    </ul>
                    <div class="best-sale">Best Sale</div>
                </div>
            </div>

            <div class="col-lg-3 col-md-6">
                <div class="single-pricing-table" data-aos="fade-up" data-aos-delay="70" data-aos-duration="700" data-aos-once="true">
                    <div class="pricing-header">
                        <h3>@language.Getkey("Pricing_Index_h_Premium")</h3>
                    </div>
                    <div class="price">$30 <span>@language.Getkey("Pricing_Index_span_PerMonthly")</span></div>
                    <div class="pricing-btn">
                        <a asp-area="" asp-controller="Contact" asp-action="Index" class="default-btn">@language.Getkey("Pricing_Index_a_ChooseThisPlan")</a>
                    </div>
                    <ul class="features-list">
                        <li><i class="ri-check-line"></i> Free Mobile & Online App</li>
                        <li><i class="ri-check-line"></i> Online System</li>
                        <li><i class="ri-check-line"></i> Data full Access</li>
                        <li><i class="ri-check-line"></i> 1 Business Mastercard</li>
                        <li><i class="ri-check-line"></i> International Payment</li>
                        <li><i class="ri-check-line"></i> Support Unlimited</li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-3 col-md-6">
                <div class="single-pricing-table" data-aos="fade-up" data-aos-delay="70" data-aos-duration="700" data-aos-once="true">
                    <div class="pricing-header">
                        <h3>@language.Getkey("Pricing_Index_h_Premium")</h3>
                    </div>
                    <div class="price">$99 <span>@language.Getkey("Pricing_Index_span_PerMonthly")</span></div>
                    <div class="pricing-btn">
                        <a asp-area="" asp-controller="Contact" asp-action="Index" class="default-btn">@language.Getkey("Pricing_Index_a_ChooseThisPlan")</a>
                    </div>
                    <ul class="features-list">
                        <li><i class="ri-check-line"></i> Free Mobile & Online App</li>
                        <li><i class="ri-check-line"></i> Online System</li>
                        <li><i class="ri-check-line"></i> Data full Access</li>
                        <li><i class="ri-check-line"></i> 1 Business Mastercard</li>
                        <li><i class="ri-check-line"></i> International Payment</li>
                        <li><i class="ri-check-line"></i> Support Unlimited</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

prj_KohinorWeb/Views/Shared/_OurPlansPLUS.cshtml
@{
    ViewData["Title"] = "Our Plans Section";
}

<div class="global-transfers-area pt-100 pb-75">
    <div class="container">
        <div class="section-title">
            <span>@language.Getkey("Pricing_Index_Span_OurPricingPlans")</span>
            <h2>@language.Getkey("Pricing_Index_h_OurPricingPlans_Desc")</h2>
        </div>

        <div class="row justify-content-center">
            <div class="col-lg-3 col-md-6">
                <div class="single-pricing-table" data-aos="fade-up" data-aos-delay="50" data-aos-duration="500" data-aos-once="true">
                    <div class="pricing-header">
                        <h3>@language.Getkey("Pricing_Index_h_Standard")</h3>
                    </div>
                    <div class="price">$20 <span>@language.Getkey("Pricing_Index_span_PerMonthly")</span></div>
                    <div class="pricing-btn">
                        <a asp-area="" asp-controller="Contact" asp-action="Index" class="default-btn">@language.Getkey("Pricing_Index_a_ChooseThisPlan")</a>
                    </div>
                    <ul class="features-list">
                        <li><i class="ri-check-line"></i> Free Mobile & Online App</li>
                        <li><i class="ri-check-line"></i> Online System</li>
                        <li><i class="ri-check-line"></i> Data full Access</li>
                        <li><i class="ri-check-line"></i> 1 Business Mastercard</li>
                        <li><i class="ri-check-line"></i> International Payment</li>
                        <li><i class="ri-check-line"></i> Support Unlimited</li>
                    </ul>
                </div>
            </div>

            <div class="col-lg-3 col-md-6">
                <div class="single-pricing-table" data-aos="fade-up" data-aos-delay="60" data-aos-duration="600" data-aos-once="true">
                    <div class="pricing-header">
                        <h3>@language.Getkey("Pricing_Index_h_Business")</h3>
                    </div>
                    <div class="price">$25 <span>@language.Getkey("Pricing_Index_span_PerMonthly")</span></div>
                    <div class="pricing-btn">
                        <a asp-area="" asp-controller="Contact" asp-action="Index" class="default-btn">@language.Getkey("Pricing_Index_a_ChooseThisPlan")</a>
                    </div>
                    <ul class="features-list">
                        <li><i class="ri-check-line"></i> Free Mobile & Online App</li>
                        <li><i class="ri-check-line"></i> Online System</li>
                        <li><i class="ri-check-line"></i> Data full Access</li>
                        <li><i class="ri-check-line"></i> 1 Business Mastercard</li>
                        <li><i class="ri-check-line"></i> International Payment</li>
                        <li><i class="ri-check-line"></i> Support Unlimited</li>
                    </ul>
                    <div class="best-sale">Best Sale</div>
                </div>
            </div>

            <div class="col-lg-3 col-md-6">
                <div class="single-pricing-table" data-aos="fade-up" data-aos-delay="70" data-aos-duration="700" data-aos-once="true">
                    <div class="pricing-header">
                        <h3>@language.Getkey("Pricing_Index_h_Premium")</h3>
                    </div>
                    <div class="price">$30 <span>@language.Getkey("Pricing_Index_span_PerMonthly")</span></div>
                    <div class="pricing-btn">
                        <a asp-area="" asp-controller="Contact" asp-action="Index" class="default-btn">@language.Getkey("Pricing_Index_a_ChooseThisPlan")</a>
                    </div>
                    <ul class="features-list">
                        <li><i class="ri-check-line"></i> Free Mobile & Online App</li>
                        <li><i class="ri-check-line"></i> Online System</li>
                        <li><i class="ri-check-line"></i> Data full Access</li>
                        <li><i class="ri-check-line"></i> 1 Business Mastercard</li>
                        <li><i class="ri-check-line"></i> International Payment</li>
                        <li><i class="ri-check-line"></i> Support Unlimited</li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-3 col-md-6">
                <div class="single-pricing-table" data-aos="fade-up" data-aos-delay="70" data-aos-duration="700" data-aos-once="true">
                    <div class="pricing-header">
                        <h3>@language.Getkey("Pricing_Index_h_Premium")</h3>
                    </div>
                    <div class="price">$99 <span>@language.Getkey("Pricing_Index_span_PerMonthly")</span></div>
                    <div class="pricing-btn">
                        <a asp-area="" asp-controller="Contact" asp-action="Index" class="default-btn">@language.Getkey("Pricing_Index_a_ChooseThisPlan")</a>
                    </div>
                    <ul class="features-list">
                        <li><i class="ri-check-line"></i> Free Mobile & Online App</li>
                        <li><i class="ri-check-line"></i> Online System</li>
                        <li><i class="ri-check-line"></i> Data full Access</li>
                        <li><i class="ri-check-line"></i> 1 Business Mastercard</li>
                        <li><i class="ri-check-line"></i> International Payment</li>
                        <li><i class="ri-check-line"></i> Support Unlimited</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>