prj_KohinorWeb/Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using prj_KohinorWeb.Models;
using prj_KohinorWeb.Services;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Threading.Tasks;

namespace prj_KohinorWeb.Controllers
{
    public class ContactController : Controller
    {
        private readonly ILogger<ContactController> _logger;
        private readonly HttpClient _httpClient;
        private readonly EmailService _emailService;
        private readonly string _password = "ATATT3xFfGF0k9EZznDfnoKVVhwQ3FszS7J2Kp12iAshyvXg3LgnnC8aeSwgHcA-maS41lIboJY5ErWdQ2KLx0zJOAzQXoOjANSZYzRvvaioAbnEWy1vapq9XDJwdOE6_cLyxyRIm7dMF-ZGKagqom1dCfULxsU3lo3SYfkKRG41frxj6VWa_EQ=CD792A20"; // Replace with your actual API token
        private readonly string _username = "kevin.diaz@kohinorec.com";
      

        public ContactController(ILogger<ContactController> logger, HttpClient httpClient, EmailService emailService)
        {
            _logger = logger;
            _httpClient = httpClient;
            _emailService = emailService;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Support()
        {
            return View();
        }
        public IActionResult OrderSent()
        {
            return View();
        }
        [HttpPost]
        public async Task<JsonResult> SubmitContactForm([FromBody] ContactFormModel model)
        {
            if (!ModelState.IsValid)
            {
                return Json(new { success = false, message = "Por favor, completa todos los campos correctamente." });
            }
            try
            {

                var (isSuccess, message) = await _emailService.SendContactEmail(model);

                return Json(new { success = isSuccess, message });
            }
            catch (Exception ex)
            {

                return Json(new { success = false, message = "Ocurrió un error al enviar el formulario. Inténtalo de nuevo más tarde." });
            }
        }
        [HttpPost]
        public async Task<IActionResult> SubmitForm(WorkOrderViewModel formData)
        {
            // Construct the description parameter
            var description = new StringBuilder();
            description.AppendLine($"Nombre: {formData.Name}");
            description.AppendLine($"Email: {formData.Email}");
            description.AppendLine($"Telefono: {formData.PhoneNumber}");
            description.AppendLine($"Requerimiento: {formData.Subject}");
            description.AppendLine($"Empresa: {formData.Company}");
            description.AppendLine($"Instrucciones: {formData.Description}");

            // Create the payload
            var issuePayload = new IssuePayload
            {
                fields = new Fields
                {
                    project = new Project { key = "KDBSWEB" },
                    summary = formData.Subject,
                    description = description.ToString(),
                    issuetype = new IssueType { name = "Task" }
                }
            };

            // Convert the form data to JSON
            var jsonData = JsonConvert.SerializeObject(issuePayload);
            var content = new StringContent(jsonData, Encoding.UTF8, "application/json");

            // Encode the username and password for Basic Authentication
            var credentials = Convert.ToBase64String(Encoding.ASCII.GetBytes($"{_username}:{_password}"));
            _httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Basic", credentials);

            // Send the POST request to the API
            var response = await _httpClient.PostAsync("https://kohinor-team.atlassian.net/rest/api/2/issue", content);

            if (response.IsSuccessStatusCode)
            {
                // Set success message and return the view with the message
                ViewData["Message"] = "Your message has been sent successfully!";
            }
            else
            {
                // Set error message and return the view with the message
                ViewData["Message"] = "An error occurred while sending your message. Please try again.";
            }

            // Return the same view with the message
            return View("OrderSent"); // Make sure the view name matches your actual view name
        }
    }
}

prj_KohinorWeb/Controllers/HomeController.cs
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using prj_KohinorWeb.Models;
using prj_KohinorWeb.Services;
using System.Diagnostics;

namespace prj_KohinorWeb.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly EmailService _emailService;

        public HomeController(ILogger<HomeController> logger, EmailService emailService)
        {
            _logger = logger;
            _emailService = emailService;
        }

        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Privacy()
        {
            return View();
        }
        public IActionResult Terms()
        {
            return View();
        }
        public IActionResult LITE()
        {
            return View();
        }
        public IActionResult PLUS()
        {
            return View();
        }
        public IActionResult BASIC()
        {
            return View();
        }
        public IActionResult PRO()
        {
            return View();
        }
        public IActionResult LEGACY()
        {
            return View();
        }


        [HttpPost]
        public async Task<JsonResult> SubmitForm([FromBody] ContactFormModel model)
        {
            if (!ModelState.IsValid)
            {
                return Json(new { success = false, message = "Por favor, completa todos los campos correctamente." });
            }

            try
            {
                
                var (isSuccess, message) = await _emailService.SendEmail(model);

                return Json(new { success = isSuccess, message });
            }
            catch (Exception ex)
            {
                
                return Json(new { success = false, message = "Ocurrió un error al enviar el formulario. Inténtalo de nuevo más tarde." });
            }
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        public IActionResult ChangeLanguage(string culture)
        {
            Response.Cookies.Append(CookieRequestCultureProvider.DefaultCookieName,
                CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
                new CookieOptions() { Expires = DateTimeOffset.UtcNow.AddYears(1) });

            return Redirect(Request.Headers["Referer"].ToString());
        }
    }
}

prj_KohinorWeb/Controllers/PrincingController.cs
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using prj_KohinorWeb.Models;
using System.Diagnostics;

namespace prj_KohinorWeb.Controllers
{
    public class PricingController : Controller
    {
        private readonly ILogger<PricingController> _logger;

        public PricingController(ILogger<PricingController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

    }
}

prj_KohinorWeb/Views/Home/BASIC.cshtml
<!-- Start Main Banner Area -->
<div class="main-hero-area">
    <div class="container-fluid">
        <div class="row align-items-center justify-content-around">
            <div class="col-lg-9 col-md-12" data-aos="fade-right" data-aos-delay="50" data-aos-duration="500" data-aos-once="true">
                <div class="main-hero-content">
                    <span><i class="ri-lock-line"></i>@language.Getkey("Home_Index_Span_SimpleQuickSecure")</span>

                    <h1>@language.Getkey("Home_Business_h_Main_Title")</h1>
                    <p>@language.Getkey("Home_Business_span_Main_Desc")</p>

                    <div class="banner-btn">
                        <a asp-area="" asp-controller="Contact" asp-action="Index" class="default-btn">@language.Getkey("Home_Index_Anchor_ContactNow")</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="main-banner-shape" data-speed="0.08" data-revert="true">
        <img src="~/Snuff/assets/images/main-banner/shape-1.png" alt="image">
    </div>
    <div class="main-hero-shape">
        <img src="~/Snuff/assets/images/main-banner/shape-3.png" alt="image">
    </div>
    <div class="main-hero-shape-2">
        <img src="~/Snuff/assets/images/main-banner/shape-4.png" alt="image">
    </div>
</div>
<!-- End Main Banner Area -->
<!-- Start Business Advantages Area -->
<div class="reliable-area ptb-100">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-6 col-md-12">
                <div class="reliable-image" data-aos="fade-right" data-aos-delay="50" data-aos-duration="500" data-aos-once="true">
                    <img src="~/Snuff/assets/images/reliable/reliable.png" alt="image">

                    <div class="reliable-shape">
                        <img src="~/Snuff/assets/images/reliable/shape-1.png" alt="image">
                    </div>
                </div>
            </div>

            <div class="col-lg-6 col-md-12">
                <div class="reliable-content" data-aos="fade-left" data-aos-delay="50" data-aos-duration="500" data-aos-once="true">
                    <span>@language.Getkey("Home_Basic_span_Title")</span>
                    <h3>@language.Getkey("Home_Basic_h_Title")</h3>
                    <p>@language.Getkey("Home_Basic_p_Description")</p>

                    <div class="row justify-content-center">
                        <div class="col-lg-6 col-md-6">
                            <ul class="reliable-list">
                                <li><i class="ri-check-line"></i>@language.Getkey("Home_Basic_li_Sales")</li>
                                <li><i class="ri-check-line"></i>@language.Getkey("Home_Basic_li_Purchases_FirstFree")</li>
                                <li><i class="ri-check-line"></i>@language.Getkey("Home_Basic_li_Documents")</li>
                            </ul>
                        </div>

                        <div class="col-lg-6 col-md-6">
                            <ul class="reliable-list">
                                <li><i class="ri-check-line"></i>@language.Getkey("Home_Basic_li_Inventory")</li>
                                <li><i class="ri-check-line"></i>@language.Getkey("Home_Basic_li_Imports_First5Free")</li>
                                <li><i class="ri-check-line"></i>@language.Getkey("Home_Basic_li_BasicSecurity")</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>
<!-- End Business Advantages Area --
<!-- Start Kohinor Benefits Area -->
<partial name="_Benefits" asp-page="~/Views/Shared/_Benefits.cshtml" />
<!-- End Kohinor Benefits Area -->
<!-- Start Pricing Area -->
@*<partial name="_OurPlansBASIC" asp-page="~/Views/Shared/_OurPlansBASIC.cshtml" />*@
<!-- End Pricing Area -->
<!-- Start Compare Pricing Area -->
@*<partial name="_ComparePricing" asp-page="~/Views/Shared/_ComparePricing.cshtml" />*@
<!-- End Compare Pricing Area -->
<!-- Start Modules Area -->
<div class="benefits-area pt-100 pb-75" style="background-color: var(--optional-color);">
    <div class="container">
        <div class="section-title">
            <span>@language.Getkey("Pricing_Index_Span_Modules")</span>
            <h2 class="text-white">@language.Getkey("Pricing_Index_h_Modules_Title")</h2>
        </div>

        <div class="row justify-content-center">
            <div class="col-lg-6 col-sm-6" id="m_1">
                <div id="ms_1" class="single-benefits-card" data-aos="fade-up" data-aos-delay="30" data-aos-duration="300" data-aos-once="true">
                    <div class="benefits-content row flex-lg-row flex-sm-column-reverse">
                        <div class="col-md-12 col-lg-2 d-flex align-items-center justify-content-center mt-md-4 mt-lg-0">
                            <img src="~/Kohinor/images/icons/1-min.png" />
                        </div>
                        <div class="col-md-12 col-lg-10">
                            <h3>@language.Getkey("Pricing_Index_h_Modules_1")</h3>
                            <p>@language.Getkey("Pricing_Index_p_Modules_1")</p>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-lg-6 col-sm-6" id="m_2">
                <div id="ms_2" class="single-benefits-card" data-aos="fade-up" data-aos-delay="40" data-aos-duration="400" data-aos-once="true">
                    <div class="benefits-content row flex-lg-row flex-sm-column-reverse">
                        <div class="col-md-12 col-lg-2 d-flex align-items-center justify-content-center mt-md-4 mt-lg-0">
                            <img src="~/Kohinor/images/icons/2-min.png" />
                        </div>
                        <div class="col-md-12 col-lg-10">
                            <h3>@language.Getkey("Pricing_Index_h_Modules_2")</h3>
                            <p>@language.Getkey("Pricing_Index_p_Modules_2")</p>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-lg-6 col-sm-6" id="m_3">
                <div id="ms_3" class="single-benefits-card" data-aos="fade-up" data-aos-delay="50" data-aos-duration="500" data-aos-once="true">
                    <div class="benefits-content row flex-lg-row flex-sm-column-reverse">
                        <div class="col-md-12 col-lg-2 d-flex align-items-center justify-content-center mt-md-4 mt-lg-0">
                            <img src="~/Kohinor/images/icons/3-min.png" />
                        </div>
                        <div class="col-md-12 col-lg-10">
                            <h3>@language.Getkey("Pricing_Index_h_Modules_3")</h3>
                            <p>@language.Getkey("Pricing_Index_p_Modules_3")</p>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-lg-6 col-sm-6" id="m_4">
                <div id="ms_4" class="single-benefits-card" data-aos="fade-up" data-aos-delay="60" data-aos-duration="600" data-aos-once="true">
                    <div class="benefits-content row flex-lg-row flex-sm-column-reverse">
                        <div class="col-md-12 col-lg-2 d-flex align-items-center justify-content-center mt-md-4 mt-lg-0">
                            <img src="~/Kohinor/images/icons/4-min.png" />
                        </div>
                        <div class="col-md-12 col-lg-10">
                            <h3>@language.Getkey("Pricing_Index_h_Modules_4")</h3>
                            <p>@language.Getkey("Pricing_Index_p_Modules_4")</p>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-lg-6 col-sm-6" id="m_10">
                <div id="ms_10" class="single-benefits-card" data-aos="fade-up" data-aos-delay="80" data-aos-duration="800" data-aos-once="true">
                    <div class="benefits-content row flex-lg-row flex-sm-column-reverse">
                        <div class="col-md-12 col-lg-2 d-flex align-items-center justify-content-center mt-md-4 mt-lg-0">
                            <img src="~/Kohinor/images/icons/10-min.png" />
                        </div>
                        <div class="col-md-12 col-lg-10">
                            <h3>@language.Getkey("Pricing_Index_h_Modules_10")</h3>
                            <p>@language.Getkey("Pricing_Index_p_Modules_10")</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End Modules Area -->
<!-- Start Clients Area -->
<partial name="_OurClients" asp-page="~/Views/Shared/_OurClients.cshtml" />
<!-- End Clients Area -->
<!-- Start Overview Area -->
<partial name="_Overview" asp-page="~/Views/Shared/_Overview.cshtml" />
<!-- End Overview Area -->
@section scripts{
    <script>
        // jQuery
        $(document).ready(function () {
            $("#mainHeader").removeClass("main-header-area");
        });
    </script>
    <style>
        .main-hero-area {
            background-image: url('../../../kohinor/images/home/banner_5.jpg');
            background-position: center right;
        }
    </style>
}

prj_KohinorWeb/Views/Home/PRO.cshtml
<!-- Start Main Banner Area -->
<div class="main-hero-area">
    <video class="background-video" autoplay loop muted playsinline>
        <source src="~/Kohinor/images/home/banner_7.mp4" type="video/mp4" />
    </video>
    <div class="container-fluid">
        <div class="row align-items-center">
            <div class="col-lg-8 col-md-12" data-aos="fade-right" data-aos-delay="50" data-aos-duration="500" data-aos-once="true">
                <div class="main-hero-content">
                    <span><i class="ri-lock-line"></i>@language.Getkey("Home_Index_Span_SimpleQuickSecure")</span>
                    <h1>@language.Getkey("Home_Index_h_hero_MainTitle")</h1>

                    <p class="text-white">
                        @language.Getkey("Home_Index_p_hero_MainTitle")
                        <a asp-area="" asp-controller="Pricing" asp-action="Index">@language.Getkey("Home_Index_Anchor_LearnMore")</a>
                    </p>

                    <div class="banner-btn">
                        <a asp-area="" asp-controller="Contact" asp-action="Index" class="default-btn">@language.Getkey("Home_Index_Anchor_ContactNow")</a>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-md-12" data-aos="fade-left" data-aos-delay="50" data-aos-duration="500" data-aos-once="true">
                <form class="money-transfer-form-two">
                    <div class="money-transfer-content">
                        <h3>@language.Getkey("Home_Index_form_h_Hero_ContactInformation")</h3>

                        <div class="form-group mb-3">
                            <label for="full-name">@language.Getkey("Home_Index_form_label_Hero_FullName")</label>
                            <input type="text" id="full-name" name="full-name" class="form-control" autocomplete="off" placeholder="@language.Getkey("Home_Index_form_ph_Hero_FullName")" required>
                        </div>
                        <div class="form-group mb-3">
                            <label for="phone">@language.Getkey("Home_Index_form_label_Hero_PhoneNumber")</label>
                            <input type="tel" id="phone" name="phone" class="form-control" autocomplete="off" placeholder="@language.Getkey("Home_Index_form_ph_Hero_PhoneNumber")" required>
                        </div>

                        <div class="form-group mb-3">
                            <label for="company">@language.Getkey("Home_Index_form_label_Hero_PhoneNumber")</label>
                            <input type="text" id="company" name="company" class="form-control" autocomplete="off" placeholder="@language.Getkey("Home_Index_form_ph_Hero_Company")" required>
                        </div>

                        <div class="form-group mb-3">
                            <label for="email">@language.Getkey("Home_Index_form_label_Hero_Email")</label>
                            <input type="email" id="email" name="email" class="form-control" autocomplete="off" placeholder="@language.Getkey("Home_Index_form_ph_Hero_Email")" required>
                        </div>

                        <div class="amount-delivery-time">
                            <span>@language.Getkey("Home_Index_form_span_Hero_ContactSoon")</span>
                        </div>

                        <ul class="amount-btn-group">
                            <li>
                                <a href="compare-pricing.html" class="default-btn">@language.Getkey("Home_Index_form_btn_Hero_ComparePrice")</a>
                            </li>
                            <li>
                                <button type="button" class="optional-btn">@language.Getkey("Home_Index_form_btn_Hero_GetStarted")</button>
                            </li>
                        </ul>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<!-- End Main Banner Area -->
<!-- Start Business Advantages Area -->
<div class="reliable-area ptb-100">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-6 col-md-12">
                <div class="reliable-image" data-aos="fade-right" data-aos-delay="50" data-aos-duration="500" data-aos-once="true">
                    <img src="~/Snuff/assets/images/reliable/reliable.png" alt="image">

                    <div class="reliable-shape">
                        <img src="~/Snuff/assets/images/reliable/shape-1.png" alt="image">
                    </div>
                </div>
            </div>

            <div class="col-lg-6 col-md-12">
                <div class="reliable-content" data-aos="fade-left" data-aos-delay="50" data-aos-duration="500" data-aos-once="true">
                    <span>@language.Getkey("Home_Business_span_Advantages")</span>
                    <h3>@language.Getkey("Home_Business_span_Advantages_Title")</h3>
                    <p>@language.Getkey("Home_Business_p_Advantages_Desc")</p>

                    <div class="row justify-content-center">
                        <div class="col-lg-6 col-md-6">
                            <ul class="reliable-list">
                                <li><i class="ri-check-line"></i>@language.Getkey("Home_Business_li_Advantages_1")</li>
                                <li><i class="ri-check-line"></i>@language.Getkey("Home_Business_li_Advantages_2")</li>
                                <li><i class="ri-check-line"></i>@language.Getkey("Home_Business_li_Advantages_3")</li>
                            </ul>
                        </div>

                        <div class="col-lg-6 col-md-6">
                            <ul class="reliable-list">
                                <li><i class="ri-check-line"></i>@language.Getkey("Home_Business_li_Advantages_4")</li>
                                <li><i class="ri-check-line"></i>@language.Getkey("Home_Business_li_Advantages_5")</li>
                                <li><i class="ri-check-line"></i>@language.Getkey("Home_Business_li_Advantages_6")</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End Business Advantages Area -->
<!-- Start Kohinor Benefits Area -->
<partial name="_Benefits" asp-page="~/Views/Shared/_Benefits.cshtml" />
<!-- End Kohinor Benefits Area -->
<!-- Start Paiement Area -->
<div class="paiement-area ptb-100">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-6 col-md-12">
                <div class="paiement-content" data-aos="fade-right" data-aos-delay="50" data-aos-duration="500" data-aos-once="true">
                    <span>Paiement Services Worldwide</span>
                    <h3>Easily Grow Your Business Save More Money</h3>
                    <p>Lorem ipsum dolor sit amet consectetur adipiscing elit. Volutpat nisl bibendum vitae consequat. Nisl ut sed accumsan congue tempus fringilla diam arcu. Venenatis nulla senectus risus sagittis.</p>

                    <div class="row justify-content-center">
                        <div class="col-lg-6 col-md-6">
                            <ul class="paiement-list">
                                <li><i class="ri-check-line"></i> Reliable Online Payment</li>
                                <li><i class="ri-check-line"></i> Low Transaction Fee</li>
                                <li><i class="ri-check-line"></i> Affordable Security Packages</li>
                            </ul>
                        </div>

                        <div class="col-lg-6 col-md-6">
                            <ul class="paiement-list">
                                <li><i class="ri-check-line"></i> Best Networking</li>
                                <li><i class="ri-check-line"></i> Secure Payment Service</li>
                                <li><i class="ri-check-line"></i> Real Time Money Tracking</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-lg-6 col-md-12">
                <div class="paiement-image" data-aos="fade-up" data-aos-delay="50" data-aos-duration="500" data-aos-once="true">
                    <img src="~/Snuff/assets/images/paiement.png" alt="image">
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End Paiement Area -->
<!-- Start Pricing Area -->
<div class="pricing-area pb-75">
    <div class="container">
        <div class="section-title">
            <span>Our Pricing Plan</span>
            <h2>We Charge As Little As Possible. No Subscription Fee</h2>
        </div>

        <div class="row justify-content-center">
            <div class="col-lg-4 col-md-6">
                <div class="single-pricing-table" data-aos="fade-up" data-aos-delay="50" data-aos-duration="500" data-aos-once="true">
                    <div class="pricing-header">
                        <h3>Basic</h3>
                    </div>
                    <div class="price">$15 <span>Per Monthly</span></div>
                    <div class="pricing-btn">
                        <a href="pricing.html" class="default-btn">Choose This Plan</a>
                    </div>
                    <ul class="features-list">
                        <li><i class="ri-check-line"></i> Free Mobile & Online App</li>
                        <li><i class="ri-check-line"></i> Online System</li>
                        <li><i class="ri-check-line"></i> Data full Access</li>
                        <li><i class="ri-check-line"></i> 1 Business Mastercard</li>
                        <li><i class="ri-check-line"></i> International Payment</li>
                        <li><i class="ri-check-line"></i> Support Unlimited</li>
                    </ul>
                </div>
            </div>

            <div class="col-lg-4 col-md-6">
                <div class="single-pricing-table" data-aos="fade-up" data-aos-delay="60" data-aos-duration="600" data-aos-once="true">
                    <div class="pricing-header">
                        <h3>Standard</h3>
                    </div>
                    <div class="price">$70 <span>Per Monthly</span></div>
                    <div class="pricing-btn">
                        <a href="pricing.html" class="default-btn">Choose This Plan</a>
                    </div>
                    <ul class="features-list">
                        <li><i class="ri-check-line"></i> Free Mobile & Online App</li>
                        <li><i class="ri-check-line"></i> Online System</li>
                        <li><i class="ri-check-line"></i> Data full Access</li>
                        <li><i class="ri-check-line"></i> 1 Business Mastercard</li>
                        <li><i class="ri-check-line"></i> International Payment</li>
                        <li><i class="ri-check-line"></i> Support Unlimited</li>
                    </ul>
                    <div class="best-sale">Best Sale</div>
                </div>
            </div>

            <div class="col-lg-4 col-md-6">
                <div class="single-pricing-table" data-aos="fade-up" data-aos-delay="70" data-aos-duration="700" data-aos-once="true">
                    <div class="pricing-header">
                        <h3>Premium</h3>
                    </div>
                    <div class="price">$99 <span>Per Monthly</span></div>
                    <div class="pricing-btn">
                        <a href="pricing.html" class="default-btn">Choose This Plan</a>
                    </div>
                    <ul class="features-list">
                        <li><i class="ri-check-line"></i> Free Mobile & Online App</li>
                        <li><i class="ri-check-line"></i> Online System</li>
                        <li><i class="ri-check-line"></i> Data full Access</li>
                        <li><i class="ri-check-line"></i> 1 Business Mastercard</li>
                        <li><i class="ri-check-line"></i> International Payment</li>
                        <li><i class="ri-check-line"></i> Support Unlimited</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End Pricing Area -->
<!-- Start Modules Area -->
<partial name="_Modules" asp-page="~/Views/Shared/_Modules.cshtml" />
<!-- End Modules Area -->
<!-- Start Features Area -->
<partial name="_OurFeatures" asp-page="~/Views/Shared/_OurFeatures.cshtml" />
<!-- End Features Area -->
<!-- Start Clients Area -->
<partial name="_OurClients" asp-page="~/Views/Shared/_OurClients.cshtml" />
<!-- End Clients Area -->
<!-- Start Overview Area -->
<partial name="_Overview" asp-page="~/Views/Shared/_Overview.cshtml" />
<!-- End Overview Area -->
@section scripts{
    <script>
        // jQuery
        $(document).ready(function () {
            $("#mainHeader").removeClass("main-header-area");
        });
    </script>
    <style>
        .main-hero-area {
            background-image: url('../../../kohinor/images/home/banner_6.jpg');
            background-position: center left;
        }
        .background-video {
            position: absolute;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            object-fit: cover;
            z-index: -1;
            pointer-events: none; 
        }
        
    </style>
}